version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/backend" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "docker"
    directories:
      - "src/backend"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "docker-compose"
    directories:
      - "/"
      # - "/infra/*/"
    schedule:
      interval: "weekly"
