services:
  postgres-db:
    image: postgres:17.0
    container_name: postgres-db
    restart: unless-stopped
    volumes:
      - ./docker_data/postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-records}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      TZ: Pacific/Auckland