global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'records-api'
    static_configs:
      - targets: [ 'records-backend:8081' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]