@base_api_address = http://localhost:8080
@auth_v1_api_address = {{base_api_address}}/api/v1/auth

GET {{auth_v1_api_address}}
Accept: application/json

###

POST {{auth_v1_api_address}}/jwt
Accept: application/json
Content-Type: application/json

{
  "Email": "stephen.hawking@records.invalid",
  "Password": "password"
}

###

PUT {{auth_v1_api_address}}
Accept: application/json

{
    "FirstName": "Isaac",
    "LastName": "Newton",
    "Email": "isaac.newton@example.invalid",
    "Password": "password"
}
###

DELETE {{auth_v1_api_address}}/guid