name: Build and Test

on:
  push:
    branches:
      - '**' # Run on all branches
    tags-ignore:
      - '**' # Ignore all tags, they get their own workflow
  workflow_call:

jobs:
  build_and_test_backend:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        dotnet-version: ['8.0.x']
    env:
      working-directory: ./src/backend
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
     
      - name: Install dependencies
        run: dotnet restore
        working-directory: ${{ env.working-directory }}
     
      - name: Build backend
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{ env.working-directory }}

      # TODO: run unit tests

      # TODO: run integration tests
