name: Build and Test

on:
  push:
    branches:
      - '**' # Run on all branches
    tags-ignore:
      - '**' # Ignore all tags, they get their own workflow
  workflow_call:

jobs:
  build_and_test_backend:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        dotnet-version: ['8.0.x']
    env:
      backend-directory: ./src/backend/Records
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
     
      - name: Install dependencies
        run: dotnet restore
        working-directory: ${{ env.backend-directory }}
     
      - name: Build backend
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{ env.backend-directory }}

      - name: Run unit tests
        run: dotnet test UnitTests --no-restore --verbosity normal
        working-directory: ${{ env.backend-directory }}

      - name: Run integration tests
        run: dotnet test IntegrationTests --no-restore --verbosity normal
        working-directory: ${{ env.backend-directory }}

  # build_and_push_web_api_image:
  #   runs-on: ubuntu-latest
  #   needs: ['build_and_test_backend']
  #   timeout-minutes: 30
  #   if: github.ref_name != 'master'
  #   permissions:
  #     packages: write
  #     contents: read
  #     attestations: write
  #     id-token: write

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Set up Docker QEMU Emulation
  #       uses: docker/setup-qemu-action@v3

  #     - name: Setup Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Log In to the Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
      
  #     - name: Extract metadata (tags, labels) for the web API image
  #       id: webapi-metadata
  #       uses: docker/metadata-action@v5
  #       with: 
  #         images: |
  #           ghcr.io/${{ github.repository }}/webapi
  #         tags: |
  #           type=ref,enable=true,prefix=dev_,suffix=_${{ github.run_number }},event=branch

  #     - name: Docker Build and Push Web API
  #       id: webapi-push
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: src/backend/Records
  #         file: src/backend/Records/WebAPI/Dockerfile
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         tags: ${{ steps.webapi-metadata.outputs.tags }}
  #         labels: ${{ steps.webapi-metadata.outputs.labels }}
      
  #     - name: Generate Web API Artifact
  #       uses: actions/attest-build-provenance@v1
  #       with:
  #         subject-name: ghcr.io/${{ github.repository }}/webapi
  #         subject-digest: ${{ steps.webapi-push.outputs.digest }}
  #         push-to-registry: true
