name: Build and Test the Frontend

on:
  push:
    branches:
      - "**" # Run on all branches
      - "!releases/**"
    tags-ignore:
      - "**" # Ignore all tags, they get their own workflow
    paths:
      - "src/frontend/**"
  workflow_call:

jobs:
  # check if can build image
  build_and_test_frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        dotnet-version: ["9.0.x"]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: push
        uses: docker/build-push-action@v5
        with:
          context: ./src/frontend
          file: ./src/frontend/Dockerfile
          platforms: linux/amd64
          push: false
          tags: ghcr.io/amieldelatorre/records-frontend:test
